"""
Reticle Worker Script
"""
import sys
import json

def main():
    sys.stdin.reconfigure(encoding='utf-8')
    sys.stdout.reconfigure(encoding='utf-8')
    sys.stderr.reconfigure(encoding='utf-8')

    line = sys.stdin.readline()
    if not line: return
    
    req = json.loads(line)
    req_id = req.get("id")
    session_id = req.get("execution", req_id)
    if session_id.startswith("compile-"):
        session_id = session_id[8:]
    inputs = req.get("inputs", [])
    
    dag_json_str = ""
    for i in inputs:
        if i.get("name") == "DAG JSON":
            dag_json_str = i.get("data", "{}")
            break
            
    dag = json.loads(dag_json_str)
    
    generated_files = {}
    
    # Generate Agent YAMLs
    for agent in dag.get("agents", []):
        if not agent.get("is_new") and not agent.get("system_prompt"):
            continue
            
        agent_id = agent.get("id")
        
        agent_yaml_str = f"""id: {agent_id}
name: "{str(agent.get('name', agent_id)).replace('"', "'")}"
description: "{str(agent.get('description', '')).replace('"', "'")}"
version: 1.0.0
runtime: python
entrypoint: workers/{agent_id}.py
"""
        
        # Always print arrays for adherence to standard
        inputs_list = agent.get("inputs", [])
        if not isinstance(inputs_list, list): inputs_list = []
        agent_yaml_str += "inputs:\n"
        for inp in inputs_list:
            agent_yaml_str += f"  - \"{inp}\"\n"
            
        memory_list = agent.get("memory", [])
        if not isinstance(memory_list, list): memory_list = []
        agent_yaml_str += "memory:\n"
        for m in memory_list:
            agent_yaml_str += f"  - \"{m}\"\n"
            
        skills_list = agent.get("skills", [])
        if not isinstance(skills_list, list): skills_list = []
        agent_yaml_str += "skills:\n"
        for s in skills_list:
            agent_yaml_str += f"  - \"{s}\"\n"
                
        generated_files[f"agents/{agent_id}/{agent_id}.yaml"] = agent_yaml_str
        
    # Worker scripts are now exclusively generated by coder.py to prevent race conditions
        
    # Generate Workflow YAML
    
    workflow_id = f"workflow_{session_id}" if req.get("execution", "").startswith("compile-exec-") else "generated-workflow"
    workflow_yaml_str = f"""id: {workflow_id}
name: {dag.get('workflow_name', 'Generated Workflow')}
version: 1.0.0
nodes:"""
    for i, node in enumerate(dag.get("nodes", [])):
        workflow_yaml_str += f"""
  - id: {node.get('id')}
    agent: {node.get('agent_id')}
    parameters: {{}}"""
        
        
    workflow_yaml_str += "\nedges:"
    for edge in dag.get("edges", []):
        workflow_yaml_str += f"""
  - from: {edge.get('from')}
    to: {edge.get('to')}"""
    
        
    generated_files[f"workflows/{workflow_id}.yaml"] = workflow_yaml_str
    


    generated_files["workers/file-writer.py"] = """import sys, json, os, re, logging

logging.basicConfig(level=logging.CRITICAL)
logger = logging.getLogger(__name__)

def main():
    sys.stdin.reconfigure(encoding='utf-8')
    sys.stdout.reconfigure(encoding='utf-8')
    sys.stderr.reconfigure(encoding='utf-8')

    line = sys.stdin.readline()
    if not line: return
    
    req = json.loads(line)
    req_id = req.get("id", "unknown")
    exec_id = req.get("execution", "unknown")
    inputs = req.get("inputs", [])
    mem = req.get("memory", {})
    workspace_dir = mem.get("workspace_dir", f"./.reticle/sessions/{exec_id}")
    src_dir = os.path.join(workspace_dir, "src")
    os.makedirs(src_dir, exist_ok=True)
    
    operations_executed = 0
    errors = []
    success_log = []
    
    for inp in inputs:
        data = inp.get("data", "")
        # Extract ```json blocks
        matches = re.finditer(r'```json\\s*(.*?)\\s*```', data, re.DOTALL)
        for match in matches:
            try:
                block = json.loads(match.group(1))
                ops = block.get("file_operations", [])
                for op in ops:
                    action = op.get("action")
                    path = op.get("path")
                    clean_path = os.path.normpath(path).lstrip(os.sep)
                    if clean_path.startswith("src" + os.sep): clean_path = clean_path[4:]
                    if ".." in clean_path:
                        errors.append(f"Invalid path: {path}")
                        continue
                        
                    full_path = os.path.join(src_dir, clean_path)
                    os.makedirs(os.path.dirname(full_path), exist_ok=True)
                    
                    if action == "create":
                        content = op.get("content", "")
                        with open(full_path, "w", encoding="utf-8") as f:
                            f.write(content)
                        operations_executed += 1
                        success_log.append(f"Created: {clean_path}")
                    elif action == "edit":
                        search = op.get("search", "")
                        replace = op.get("replace", "")
                        if not os.path.exists(full_path):
                            errors.append(f"Cannot edit non-existent file: {path}")
                            continue
                        with open(full_path, "r", encoding="utf-8") as f:
                            current_content = f.read()
                        if search not in current_content:
                            errors.append(f"Search string not found in {path}")
                            continue
                        new_content = current_content.replace(search, replace, 1)
                        with open(full_path, "w", encoding="utf-8") as f:
                            f.write(new_content)
                        operations_executed += 1
                        success_log.append(f"Edited: {clean_path}")
            except Exception as e:
                pass
                
        # Extract markdown files
        file_matches = re.finditer(r'### FILE:\\s*([^\\n]+)\\n```[a-zA-Z]*\\n(.*?)```', data, re.DOTALL)
        for match in file_matches:
            try:
                path = match.group(1).strip()
                content = match.group(2)
                
                clean_path = os.path.normpath(path).lstrip(os.sep)
                if clean_path.startswith("src" + os.sep): clean_path = clean_path[4:]
                if ".." in clean_path:
                    errors.append(f"Invalid path: {path}")
                    continue
                    
                full_path = os.path.join(src_dir, clean_path)
                os.makedirs(os.path.dirname(full_path), exist_ok=True)
                
                with open(full_path, "w", encoding="utf-8") as f:
                    f.write(content)
                operations_executed += 1
                success_log.append(f"Created: {clean_path}")
            except Exception as e:
                pass
                
    result_text = f"Executed {operations_executed} file operations in src/:"
    if success_log:
        result_text += "\\n" + "\\n".join(success_log)
    if errors:
        result_text += f"\\n\\nErrors ({len(errors)}):\\n" + "\\n".join(errors)
    
    artifact = {
        "id": f"{req_id}_output",
        "name": "File Writer Output",
        "type": "text/plain",
        "data": result_text
    }
    print(json.dumps({"id": req_id, "artifact": artifact}))

if __name__ == "__main__":
    main()
"""
    
    import os
    mem = req.get("memory", {})
    workspace_dir = mem.get("workspace_dir", ".")
    
    sys.stderr.write(f"[scaffolder] Initial workspace_dir: {workspace_dir}\n")
    sys.stderr.write(f"[scaffolder] Execution ID: {req.get('execution')}\n")

        
    sys.stderr.write(f"[scaffolder] Writing {len(generated_files)} files to {workspace_dir}\n")
    for path, content in generated_files.items():
        full_path = os.path.join(workspace_dir, path)
        os.makedirs(os.path.dirname(full_path), exist_ok=True)
        with open(full_path, "w", encoding="utf-8") as f:
            f.write(content)
            
    artifact = {
        "id": f"{req_id}_output",
        "name": "YAML Files",
        "type": "application/json",
        "data": "{}"
    }
    
    print(json.dumps({
        "id": req_id,
        "artifact": artifact
    }))

if __name__ == "__main__":
    main()
